### ISSUE TITLE
很早以前提过的BUG，我这次来提供复现代码了

### ISSUE THREAD

**Issue by 1027663760** [OpenEpl/TextECode#10]
[test.zip](https://github.com/OpenEpl/TextECode/files/14097640/test.zip)

问题：基类里面的私有成员数据类型为数组时，内存访问异常(在类初始化完毕之后数组指向的内存为0)
除了整数型数组以外的数据类型，我还没测试过

![2](https://github.com/OpenEpl/TextECode/assets/26378634/4878fea7-c2dc-4d48-9b8a-7b2b6e485f25)
![1](https://github.com/OpenEpl/TextECode/assets/26378634/b11cdc1b-8d80-424d-8196-be1e68e867b2)

test.e 是正常的原始代码
2.e 是txt转e后的异常文件

**Comment by ArcticLampyrid** [comment]
似乎是由于类的声明顺序不同而触发的问题
看起来是易语言那边的bug，某些特定次序下定义类模块就会出现这种情况

**Comment by ArcticLampyrid** [comment]
https://github.com/OpenEpl/TextECode/assets/9017609/f19961ca-543d-4404-8c74-7eaad771dae0

**Comment by 1027663760** [comment]
> 2024-01-30.21-27-19.mp4

那，左边这个列表顺序被破坏的问题可以修复么？顺序变了会影响到平时找代码的习惯
![QQ图片20240131233234](https://github.com/OpenEpl/TextECode/assets/26378634/8d331e12-83eb-40a1-8640-fbb1d927494d)

**Comment by ArcticLampyrid** [comment]
顺序问题将在 #11 追踪。
