### ISSUE TITLE
文本转源码的时候提示导入模块失败，转换出来的源码变量发生偏移。

### ISSUE THREAD

**Issue by whitetools** [OpenEpl/TextECode#12]

**Comment by 1027663760** [comment]
哦吼

**Comment by ArcticLampyrid** [comment]
这个问题可以分为两部分：
- [x] 模块中的类，如果存在继承再继承的关系，则无法被正常加载 (fixed by 5818ce2)
- [x] 未加载模块时，生成的对于流程控制语句的“非预编译数据”可能存在错误 (fixed by https://github.com/OpenEpl/EProjectFile/commit/d96f6a792fc45069aa6bc048bf5a8c768ff6d50f)

**Comment by ArcticLampyrid** [comment]
我相信 v0.2.1 已经修正了相关问题，如果您仍旧遇到问题，可以在此 Issue 下继续回复
