### ISSUE TITLE
自绘窗口经过代码转换后导致背景皮肤会丢失的BUG。

### ISSUE THREAD

**Issue by whitetools** [OpenEpl/TextECode#13]
上次的BUG不会再复现了，又发现一个新BUG，对于自绘窗口。
[使用了EXUI支持库]
[BUG反馈.zip](https://github.com/user-attachments/files/16688109/BUG.zip)
![转换前](https://github.com/user-attachments/assets/3d2ca804-26bd-47f5-b940-e8f743d9263b)
![转换后](https://github.com/user-attachments/assets/82947a3c-1222-4f84-9090-55fc015d62e1)

**Comment by ArcticLampyrid** [comment]
默认情况下 TextECode 在定义**同级**窗口会保留原有的定义顺序，在出现上下级时会**先定义容器窗口组件**，再定义容器内部的窗口组件。

然而 EXUI 似乎要求 `窗口EX`（容器型窗口组件）在最后被定义才能正常工作。

易语言 IDE 确实会把最先加入的组件放在定义列表的最尾部，故我们可能需要修改规则为：在出现上下级时会定义容器内部的窗口组件，再**定义容器窗口组件**。

**Comment by ArcticLampyrid** [comment]
我们已经在 v0.2.2 中使用了新的顺序规则，这可能有助于缓解此问题。然而，仍然有一些疑问可能需要来自其它途径的解答：

#### 第一个问题
`窗口EX` 是否需要被定义为容器型窗口组件？我本人对 EXUI 并不熟悉，通过您的工程文件我看到**有且只有** `标签EX_标题栏` 被放在 `窗口EX` 容器中，其它组件则被直接放置在了 `窗口` 中。结构如下：
```xml
<窗口 名称="_启动窗口">
  <图片框EX 名称="图片框EX1">
  <按钮EX 名称="按钮EX_退出">
  <图片框EX 名称="图片框EX_刷新">
  <图片框EX 名称="图片框EX_BAR_FRONT">
  <图片框EX 名称="图片框EX_BAR_滑块">
  <图片框EX 名称="图片框EX_BAR_BG">
  <标签EX 名称="标签EX_天气_位置">
  <图片框EX 名称="图片框EX_选择夹_前景">
  <图片框EX 名称="图片框EX_选择夹_背景">
  <分组框EX 名称="分组框EX_主页_1">
    <标签EX 名称="标签EX_日期">
    <标签EX 名称="标签EX_问候语_内容">
    <标签EX 名称="标签EX_问候语_标题">
    <标签EX 名称="标签EX_时间">
  </分组框EX>
  <窗口EX 名称="窗口EX1">
    <标签EX 名称="标签EX_标题栏">
  </窗口EX>
</窗口>
```

我并不理解为什么这个 `标签EX` 如此特殊。我尝试将其直接放在 `窗口` 下，似乎并没有额外的问题出现。

#### 第二个问题
如果允许平级放置的话，`窗口EX` 本身未必是最后一个被定义的，如此似乎也会造成问题。EXUI 官方是否要求第一个放置 `窗口EX` 组件，以保证其被最后一个定义呢？

举例而言，这样操作也会导致问题：
1. 新建窗口 `窗口1`
2. 在 `窗口1` 上先放置 `标签EX`
3. 然后在 `窗口1` 上放置 `窗口EX`

这是 EXUI 设计使然吗，还是其实现中的 bug 呢？

**Comment by whitetools** [comment]
这个问题我也不是很清楚估计要问群里的大佬了，我尝试使用E2TXT，并没有遇到这样的问题，所以来反馈，不过您修复BUG的效率和对待解答问题的专业性上真的好用心，谢谢您。

**Comment by whitetools** [comment]
另外您说的那个代码顺序确实是错误的，正确的顺序确实应该是：

1新建窗口 窗口1
2然后在 窗口1 上放置 窗口EX
3在 窗口EX 上先放置 标签EX

这个EXUI界面代码是在精易论坛下载的，EXUI也强调过EXUI组件只能放在EXUI窗口容器内，所以我也不清楚这个BUG是怎么出现的。
