### ISSUE TITLE
生成出来的代码，组件会出现重复的BUG。

### ISSUE THREAD

**Issue by whitetools** [OpenEpl/TextECode#14]
也是精易论坛开源的项目，aSan易编程助手，类似于精易编程助手，这类代码窗口组件较多。
[aSan易编程助手.zip](https://github.com/user-attachments/files/16724183/aSan.zip)
![BUG反馈](https://github.com/user-attachments/assets/fab9f3de-edcd-4553-9d5b-8d05f9554a47)

**Comment by ArcticLampyrid** [comment]
唔，修了（v0.2.3），窗口组件确实没怎么测试
（所以说咱究竟又写了多少 bug 啊🥲

其它问题主要有两个（不视为 bug）：
- 查询 apk 信息程序集里面的 `GetVersion` 和精易模块导出的 `GetVersion` 子程序重名了，导致关联错误
- 自定义数据类型表里的 `节点` 和数据结构支持库提供的 `节点` 类型重名了，导致关联错误
