### ISSUE TITLE
未记录程序数据的外部程序引用表

### ISSUE THREAD

**Issue by tangguoQAQ** [OpenEpl/TextECode#2]
工作夹的第二个子夹最后的项目“外部程序引用表”数据。

**Comment by ArcticLampyrid** [comment]
文件编辑库部分已支持相关信息的解析
https://github.com/OpenEpl/EProjectFile/commit/cea914c59204e0861cff8482ffa5157e144e5ea0

TextECode部分，数据存储形式待设计
欢迎相关设计提案，初步打算在 `*.eproject` 添加一个 `ExternalFilePaths` 字段保存相关文件路径

**Comment by ArcticLampyrid** [comment]
named as `ExternalFiles`
