### ISSUE TITLE
vscode支持?

### ISSUE THREAD

**Issue by Scholar01** [OpenEpl/TextECode#3]
10月初的时候我就有过相关想法,重写e结构导出文本格式,然后对vscode开发相关插件,就可以做到在vscode里面写易语言了.

不知道是否对该支持感兴趣?

**Comment by ArcticLampyrid** [comment]
这似乎不属于本项目的范围
如果需要编写 vscode 扩展，已经可以通过命令行调用本工具

**Comment by ArcticLampyrid** [comment]
倒是对相关项目感兴趣，但是不太了解 vscode 扩展的开发（）

**Comment by ArcticLampyrid** [comment]
stale
