### ISSUE TITLE
restore 还原e源码异常

### ISSUE THREAD

**Issue by dmhai** [OpenEpl/TextECode#6]
首先感谢作者公开了这个工程，让 svn 管理源码成为可能。

不过我测试了2个最有代表性的：精易模块v11.0.5和超级模块8.0，都是 restore 失败了

它俩都是官方开源，而且代码足够复杂，E格式的各种数据结构的边边角角，几乎都有涉及到，用来测试这个最好不过。

出错代码过长，我就不贴了。直接下载最新的精易模块源码即可: https://ec.125.la/

**Comment by ArcticLampyrid** [comment]
本工具的开发是使用精易模块源码进行测试的，刚测试了下 精易模块v11.0.5，没有明显的问题

对于精易模块，restore 时的所有的报错来源于 `文本_取GB2312简体汉字笔画数` 这个子程序，然而这个子程序某种程度上本就是有点问题的：
![image1](https://user-images.githubusercontent.com/9017609/235198163-bb6f86ba-255c-4645-9c8f-8cc4ae127a87.png)

我们可以看到，这个子程序包含了一条特殊的注释，这个注释的内容中甚至带有换行符（CRLF）！这是条正常情况下无法被输入的错误注释，导致 generate 输出的代码不合法（没有对CRLF做特殊处理），继而导致 restore 时出错。

然而，由于这种注释正常情况下无法被用户输入（精易中存在的这条注释可能是通过易程序向导等方式被错误设置的），我暂时不考虑修复这个bug

注意到，易语言本身也不能很好地处理这条特殊注释，如果我们将 `文本_取GB2312简体汉字笔画数` 这个子程序复制到剪辑板，再以文本形式粘贴，也会得到不合法的文本式易代码：
![image2](https://user-images.githubusercontent.com/9017609/235199436-1de0e75f-812a-43cc-b901-e78ac37a898d.png)

**Comment by ArcticLampyrid** [comment]
测试了下超级模块8.0的代码，在被其主文件引用的相关EC（如`Super-EC-验证.ec`）都存在的情况下（restore 过程需要做名称关联，需要其引用的模块、支持库的信息），对 `超级模块8.0正式版.eproject` 进行 restore，出现的几条警告信息都是关于 `指针到整数` 重名的：
![image](https://user-images.githubusercontent.com/9017609/235201075-e9ac848a-08c8-4f05-b455-ab62826669f9.png)

这是由于老版本易语言不存在 `指针到整数` 这个命令，而超级模块内编写了一个名叫 `指针到整数` 的子程序。新版本易语言核心库由于新增了 `指针到整数` 这个命令，会和模块内的子程序重名，导致 restore 时候不知道用哪个，继而报错。

主要到，预编译失败通常并不影响生成的 *.e 文件的正常使用，这里报的也只是警告（warn）而非错误（error）。预编译失败后会将文本代码直接置入 *.e 文件中，而易语言在编译时对于这些未预编译的代码，会再度进行一次分析、关联。

不过，预编译失败的代码，可能无法享受 局部变量、程序集变量分别高亮，名称修改自动同步 等IDE特性。

**Comment by ArcticLampyrid** [comment]
测试版本为：
```shell
TextECode 0.1.0+0a915e38d58fbb6fa72a07430818d5a96e5eae7d
```

**Comment by dmhai** [comment]
了解，其实我svn的也只是自己的工程，不包括这些三方模块，只是用手上复杂模块评估下这个工具的完善度，

大大小小的模块都测了下，一轮测试下来，结果还是不错的，除了上面那两个模块，其他的都没啥问题。

提这个也只是想让这个项目更加完善，该不该修改的还是你们专业人士来吧，我就不提交代码添乱了，

这个 issue 可以关了。感谢回复。
