### ISSUE TITLE
突然发现个问题  右键菜单的那个生成文本代码  他只会生成src这个文件 同一个目录两个e运行的话就被覆盖掉了

### ISSUE THREAD

**Issue by 1592363624** [OpenEpl/TextECode#7]
突然发现个问题  右键菜单的那个生成文本代码  他只会生成src这个文件 同一个目录两个e运行的话就被覆盖掉了

**Comment by ArcticLampyrid** [comment]
By design.
建议每个目录下只存放一个工程，如果确有需要存放多个工程的，可以用 --source-set 参数指定相关目录的位置，以取代默认的 src 目录名。
